# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 08:47
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_medicinespage_medicinespagesection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinespagesection',
            name='section',
        ),
        migrations.AddField(
            model_name='medicinespage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicinespagesection',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('section_title', wagtail.wagtailcore.blocks.CharBlock(classname='full title', icon='title')), ('section_paragraph', wagtail.wagtailcore.blocks.TextBlock(icon='placeholder'))), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinespagesection',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
