# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_auto_20171012_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinespagesection',
            old_name='body',
            new_name='section',
        ),
    ]
