# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_auto_20171012_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinespagesection',
            name='intro',
        ),
    ]
